insert into public.tracks(slug,title,description,long_description,difficulty,icon,color,total_lessons,total_xp,order_index,tags) values
('acessibilidade','Acessibilidade','Construa interfaces inclusivas.','Semantica, foco, teclado, contraste, formularios acessiveis e testes de acessibilidade.','iniciante','♿','#2ECC71',8,900,13,array['frontend','a11y']),
('responsividade','Responsividade','Crie layouts para qualquer tela.','Mobile first, breakpoints, grids fluidos, imagens responsivas e testes em dispositivos.','iniciante','📱','#4DBBFF',8,920,14,array['frontend','layout']),
('projetos-praticos','Projetos Práticos','Construa produtos completos.','Projetos guiados de landing page, dashboard, app interativo, API integrada e portfolio.','intermediario','🚀','#F5A623',8,1200,15,array['projects','portfolio'])
on conflict(slug) do update set
  title=excluded.title,
  description=excluded.description,
  long_description=excluded.long_description,
  difficulty=excluded.difficulty,
  icon=excluded.icon,
  color=excluded.color,
  is_active=true,
  tags=excluded.tags;

insert into public.lessons(track_id,title,description,content,xp_reward,gem_reward,order_index,type,estimated_minutes,is_boss)
select t.id,x.title,x.description,x.content::jsonb,x.xp,x.gems,x.ord,x.type,x.minutes,x.is_boss
from public.tracks t
join (values
  ('html','Semantica profunda','Use article, aside, nav, header e footer com intenção.','[{"module":"HTML Essencial","chapter":"Semantica","title":"Estrutura com significado","text":"Semantica melhora SEO, acessibilidade e manutencao.","challenge":"Reestruture um layout com header, main, article e footer.","validation":"validar tags semanticas obrigatorias","difficulty":"basico"}]',95,1,7,'codigo',14,false),
  ('html','Midia acessivel','Imagens, videos e textos alternativos sem quebrar UX.','[{"module":"HTML Essencial","chapter":"Midia","title":"Conteudo multimidia","text":"Toda midia precisa de contexto, legenda ou alternativa.","challenge":"Crie uma secao com imagem, figure, figcaption e alt util.","validation":"validar figure, figcaption e alt","difficulty":"basico"}]',100,1,8,'codigo',15,false),
  ('html','Tabelas reais','Organize dados com caption, thead, tbody e escopos.','[{"module":"HTML Intermediario","chapter":"Dados","title":"Tabelas compreensiveis","text":"Tabelas devem comunicar relacoes entre cabecalhos e celulas.","challenge":"Monte uma tabela de ranking com caption e th scope.","validation":"validar caption, thead, tbody e scope","difficulty":"intermediario"}]',110,1,9,'codigo',16,false),
  ('html','SEO tecnico basico','Meta tags, titulo, descricao e hierarquia correta.','[{"module":"HTML Intermediario","chapter":"SEO","title":"Documento encontravel","text":"Metadados ajudam buscadores e compartilhamento social.","challenge":"Configure head com title, description e viewport.","validation":"validar title, meta description e viewport","difficulty":"intermediario"}]',115,1,10,'codigo',16,false),
  ('html','Revisao HTML','Corrija problemas comuns de markup.','[{"module":"HTML Revisao","chapter":"Fixacao","title":"Debug de estrutura","text":"HTML robusto evita layout quebrado e leitura confusa por tecnologias assistivas.","challenge":"Corrija tags mal fechadas, ordem de headings e links vazios.","validation":"validar estrutura e textos obrigatorios","difficulty":"intermediario"}]',120,1,11,'codigo',18,false),
  ('html','Projeto final HTML','Monte uma pagina semantica completa.','[{"module":"HTML Projeto","chapter":"Boss","title":"Pagina editorial completa","text":"Una semantica, formularios, listas, midia e SEO em uma entrega final.","challenge":"Construa uma pagina de trilha com navegacao, conteudo, formulario e rodape.","validation":"validar conjunto semantico final","difficulty":"avancado"}]',180,3,12,'projeto',28,true),

  ('css','Design tokens','Organize cores, espacamentos e raios com variaveis.','[{"module":"CSS Moderno","chapter":"Tokens","title":"Sistema visual","text":"Tokens reduzem repeticao e mantem consistencia.","challenge":"Crie variaveis CSS para tema, texto e bordas.","validation":"validar :root e uso de var()","difficulty":"intermediario"}]',115,1,7,'codigo',16,false),
  ('css','Estados de interface','Hover, focus-visible, disabled e active.','[{"module":"CSS Moderno","chapter":"Estados","title":"Feedback visual","text":"Estados claros deixam a interface previsivel e acessivel.","challenge":"Estilize botao com hover, focus-visible e disabled.","validation":"validar pseudo-classes principais","difficulty":"intermediario"}]',120,1,8,'codigo',17,false),
  ('css','Layouts fluidos','Use clamp, minmax e medidas relativas.','[{"module":"CSS Avancado","chapter":"Fluidez","title":"Layout que respira","text":"CSS moderno permite componentes que se adaptam sem dezenas de breakpoints.","challenge":"Crie cards fluidos com grid e clamp.","validation":"validar clamp, grid e minmax","difficulty":"avancado"}]',130,1,9,'codigo',18,false),
  ('css','Temas claro e escuro','Controle tema com atributos e variaveis.','[{"module":"CSS Avancado","chapter":"Temas","title":"Tema alternavel","text":"A mesma interface pode trocar visual sem duplicar componentes.","challenge":"Implemente variaveis para tema claro e escuro.","validation":"validar seletor de tema e variaveis","difficulty":"avancado"}]',135,1,10,'codigo',20,false),
  ('css','Revisao visual','Refatore CSS repetido e incoerente.','[{"module":"CSS Revisao","chapter":"Polimento","title":"Refino de interface","text":"Bom CSS tambem e legibilidade, consistencia e manutencao.","challenge":"Reduza duplicacao e aplique uma escala coerente.","validation":"validar tokens e classes reutilizaveis","difficulty":"intermediario"}]',140,1,11,'codigo',20,false),
  ('css','Projeto final CSS','Construa um dashboard responsivo.','[{"module":"CSS Projeto","chapter":"Boss","title":"Dashboard premium","text":"Una grid, flexbox, estados, responsividade e temas.","challenge":"Crie um dashboard completo com cards, toolbar e tabela responsiva.","validation":"validar layout final e estados","difficulty":"avancado"}]',190,3,12,'projeto',32,true),

  ('javascript','Escopo e closures','Entenda como funcoes lembram valores.','[{"module":"JS Intermediario","chapter":"Escopo","title":"Closures na pratica","text":"Closures aparecem em callbacks, eventos e factories.","challenge":"Crie uma funcao contador que preserva estado interno.","validation":"validar funcao, retorno e incremento","difficulty":"intermediario"}]',130,1,7,'codigo',18,false),
  ('javascript','Promises','Trabalhe com tarefas assincronas.','[{"module":"JS Intermediario","chapter":"Assincrono","title":"Promessas","text":"Promises representam operacoes que terminam no futuro.","challenge":"Crie uma promise que resolve uma lista de tarefas.","validation":"validar Promise, then ou async","difficulty":"intermediario"}]',135,1,8,'codigo',18,false),
  ('javascript','Async await','Leia APIs sem travar a interface.','[{"module":"JS Intermediario","chapter":"Assincrono","title":"Fluxo async","text":"async await deixa codigo assincrono mais claro.","challenge":"Use async await para buscar e renderizar dados simulados.","validation":"validar async, await e renderizacao","difficulty":"intermediario"}]',140,1,9,'codigo',20,false),
  ('javascript','LocalStorage','Persista preferencias no navegador.','[{"module":"JS Projetos","chapter":"Persistencia","title":"Estado salvo","text":"localStorage e util para preferencias e progresso local simples.","challenge":"Salve e recupere uma lista de objetivos.","validation":"validar setItem e getItem","difficulty":"intermediario"}]',140,1,10,'codigo',18,false),
  ('javascript','Revisao JS','Corrija bugs em eventos e arrays.','[{"module":"JS Revisao","chapter":"Debug","title":"Caca bugs","text":"Revisar codigo fortalece leitura e raciocinio.","challenge":"Corrija seletores, listeners e transformacoes de array.","validation":"validar DOM, eventos e map","difficulty":"intermediario"}]',145,1,11,'codigo',22,false),
  ('javascript','Projeto final JavaScript','Crie um app de tarefas com filtros.','[{"module":"JS Projeto","chapter":"Boss","title":"Task app","text":"Una DOM, eventos, arrays, storage e validacao.","challenge":"Construa um app de tarefas com criar, concluir, filtrar e persistir.","validation":"validar fluxo completo do app","difficulty":"avancado"}]',210,3,12,'projeto',36,true),

  ('react','Composicao de componentes','Quebre telas em partes reutilizaveis.','[{"module":"React Intermediario","chapter":"Composicao","title":"Componentes pequenos","text":"Composicao evita componentes grandes demais.","challenge":"Separe Card, Header e List em componentes.","validation":"validar componentes e props","difficulty":"intermediario"}]',140,1,7,'codigo',20,false),
  ('react','useEffect','Sincronize dados com efeitos.','[{"module":"React Intermediario","chapter":"Hooks","title":"Efeitos controlados","text":"useEffect conecta componente a mundo externo.","challenge":"Carregue dados simulados ao montar o componente.","validation":"validar useEffect e estado","difficulty":"intermediario"}]',145,1,8,'codigo',20,false),
  ('react','Formularios controlados','Controle inputs com state.','[{"module":"React Intermediario","chapter":"Formularios","title":"Inputs previsiveis","text":"Formularios controlados facilitam validacao e feedback.","challenge":"Crie formulario com nome, erro e submit.","validation":"validar value, onChange e submit","difficulty":"intermediario"}]',150,1,9,'codigo',22,false),
  ('react','Custom hooks','Extraia comportamento reutilizavel.','[{"module":"React Avancado","chapter":"Hooks","title":"Hook proprio","text":"Custom hooks deixam componentes mais limpos.","challenge":"Crie useLocalStorage para salvar preferencia.","validation":"validar hook, useState e efeito","difficulty":"avancado"}]',160,1,10,'codigo',24,false),
  ('react','Revisao React','Refatore props e estado.','[{"module":"React Revisao","chapter":"Refatoracao","title":"Componentes claros","text":"React bom e fluxo de dados simples e previsivel.","challenge":"Remova duplicacao e corrija renderizacao de lista.","validation":"validar props, key e estado","difficulty":"intermediario"}]',150,1,11,'codigo',22,false),
  ('react','Projeto final React','Construa um painel de progresso.','[{"module":"React Projeto","chapter":"Boss","title":"Progress dashboard","text":"Una componentes, hooks, formularios e listas.","challenge":"Crie painel com cards, filtros, formulario e persistencia local.","validation":"validar app React completo","difficulty":"avancado"}]',230,3,12,'projeto',40,true),

  ('typescript','Union types','Modele estados possiveis com seguranca.','[{"module":"TS Intermediario","chapter":"Tipos","title":"Unions","text":"Unions evitam valores impossiveis e documentam fluxo.","challenge":"Crie um tipo Status para missoes.","validation":"validar union e uso no objeto","difficulty":"intermediario"}]',130,1,6,'codigo',18,false),
  ('typescript','Generics','Crie funcoes reutilizaveis tipadas.','[{"module":"TS Intermediario","chapter":"Generics","title":"Reuso seguro","text":"Generics mantem informacao de tipo ao reutilizar logica.","challenge":"Crie uma funcao first<T> para arrays.","validation":"validar generic e retorno","difficulty":"intermediario"}]',145,1,7,'codigo',20,false),
  ('typescript','Utility types','Use Pick, Partial e Record.','[{"module":"TS Avancado","chapter":"Utility","title":"Tipos derivados","text":"Utility types reduzem duplicacao em contratos.","challenge":"Modele atualizacao parcial de perfil com Partial.","validation":"validar Partial ou Pick","difficulty":"avancado"}]',150,1,8,'codigo',22,false),
  ('typescript','Narrowing','Refine tipos em condicionais.','[{"module":"TS Avancado","chapter":"Narrowing","title":"Fluxo tipado","text":"TypeScript entende checagens e reduz incerteza.","challenge":"Valide um resultado que pode ser sucesso ou erro.","validation":"validar discriminated union","difficulty":"avancado"}]',155,1,9,'codigo',22,false),
  ('typescript','Revisao TypeScript','Corrija contratos inconsistentes.','[{"module":"TS Revisao","chapter":"Debug","title":"Tipos em ordem","text":"Erros de tipo revelam inconsistencias de dados.","challenge":"Corrija interfaces, parametros e retornos.","validation":"validar interfaces e funcoes","difficulty":"intermediario"}]',150,1,10,'codigo',20,false),
  ('typescript','Projeto final TypeScript','Modele um dominio de aprendizado.','[{"module":"TS Projeto","chapter":"Boss","title":"Dominio tipado","text":"Una objetos, unions, generics e utility types.","challenge":"Modele trilhas, licoes, progresso e recompensas.","validation":"validar dominio tipado completo","difficulty":"avancado"}]',220,3,11,'projeto',36,true),

  ('nodejs','Middleware','Intercepte requests antes da rota final.','[{"module":"Node Intermediario","chapter":"Middleware","title":"Pipeline HTTP","text":"Middlewares organizam logs, auth e validacao.","challenge":"Crie middleware de log para requests.","validation":"validar app.use e next","difficulty":"intermediario"}]',150,1,6,'codigo',22,false),
  ('nodejs','Parametros e query','Leia dados da URL com seguranca.','[{"module":"Node Intermediario","chapter":"Rotas","title":"Entrada HTTP","text":"Params e query controlam filtros e detalhes.","challenge":"Crie rota /users/:id com query include.","validation":"validar params e query","difficulty":"intermediario"}]',150,1,7,'codigo',20,false),
  ('nodejs','CRUD em memoria','Implemente criar, listar e atualizar.','[{"module":"Node Projetos","chapter":"CRUD","title":"API funcional","text":"CRUD e base de muitos backends.","challenge":"Crie endpoints GET, POST e PATCH para tarefas.","validation":"validar rotas CRUD","difficulty":"intermediario"}]',170,1,8,'codigo',26,false),
  ('nodejs','Erros e status HTTP','Responda falhas corretamente.','[{"module":"Node Avancado","chapter":"Erros","title":"Falhas previsiveis","text":"Status HTTP comunicam sucesso, erro do usuario ou erro interno.","challenge":"Retorne 400, 404 e 500 nos cenarios certos.","validation":"validar status e json","difficulty":"avancado"}]',165,1,9,'codigo',24,false),
  ('nodejs','Revisao API','Refatore uma API confusa.','[{"module":"Node Revisao","chapter":"Refatoracao","title":"API clara","text":"Backends bons sao previsiveis, testaveis e consistentes.","challenge":"Separe validacao, handlers e respostas.","validation":"validar rotas e respostas","difficulty":"intermediario"}]',160,1,10,'codigo',24,false),
  ('nodejs','Projeto final Node','Construa uma API de missoes.','[{"module":"Node Projeto","chapter":"Boss","title":"Mission API","text":"Una rotas, middleware, CRUD, validacao e erros.","challenge":"Implemente API completa para missoes e progresso.","validation":"validar API final","difficulty":"avancado"}]',240,3,11,'projeto',42,true),

  ('git','Merge e conflitos','Resolva conflitos sem perder trabalho.','[{"module":"Git Intermediario","chapter":"Colaboracao","title":"Conflitos","text":"Conflitos sao parte normal de colaboracao.","challenge":"Simule conflito e documente resolucao.","validation":"validar fluxo merge e resolucao","difficulty":"intermediario"}]',90,1,5,'teoria',14,false),
  ('git','Rebase com cuidado','Reorganize historico local.','[{"module":"Git Avancado","chapter":"Historico","title":"Rebase","text":"Rebase ajuda a manter historico linear quando usado com criterio.","challenge":"Explique quando usar rebase e quando evitar.","validation":"validar comandos rebase","difficulty":"avancado"}]',95,1,6,'teoria',16,false),
  ('git','GitHub Actions','Automatize checagens.','[{"module":"GitHub","chapter":"CI","title":"Pipeline simples","text":"CI roda testes e builds a cada push.","challenge":"Crie um workflow de build para pull requests.","validation":"validar arquivo yaml e comandos","difficulty":"avancado"}]',120,1,7,'codigo',24,false),
  ('git','Deploy flow','Prepare release com tags.','[{"module":"GitHub","chapter":"Release","title":"Entrega versionada","text":"Tags e releases ajudam a comunicar versoes.","challenge":"Simule tag, changelog e release notes.","validation":"validar tag e release","difficulty":"intermediario"}]',110,1,8,'projeto',20,true),

  ('apis','Autenticacao em APIs','Envie tokens e proteja endpoints.','[{"module":"APIs Intermediario","chapter":"Auth","title":"Requests autenticados","text":"Muitas APIs exigem token em headers.","challenge":"Monte uma request com Authorization Bearer.","validation":"validar header Authorization","difficulty":"intermediario"}]',140,1,6,'codigo',22,false),
  ('apis','Paginacao','Carregue listas grandes aos poucos.','[{"module":"APIs Intermediario","chapter":"Escala","title":"Paginas de dados","text":"Paginacao melhora performance e UX.","challenge":"Consuma pagina, limite e total de itens.","validation":"validar page e limit","difficulty":"intermediario"}]',140,1,7,'codigo',22,false),
  ('apis','Cache e revalidacao','Evite requests desnecessarias.','[{"module":"APIs Avancado","chapter":"Performance","title":"Dados eficientes","text":"Cache reduz latencia e custo.","challenge":"Implemente cache simples com timestamp.","validation":"validar cache e expiracao","difficulty":"avancado"}]',155,1,8,'codigo',24,false),
  ('apis','Projeto final APIs','Crie um cliente de dados robusto.','[{"module":"APIs Projeto","chapter":"Boss","title":"API client","text":"Una fetch, auth, erros, paginacao e cache.","challenge":"Monte uma camada de cliente para consumir missoes.","validation":"validar cliente completo","difficulty":"avancado"}]',220,3,9,'projeto',38,true),

  ('banco-de-dados','Insert e update','Grave e altere registros com seguranca.','[{"module":"SQL Intermediario","chapter":"Escrita","title":"Mudanca de dados","text":"INSERT e UPDATE precisam de filtros e validacao.","challenge":"Insira e atualize um perfil de usuario.","validation":"validar insert e update","difficulty":"intermediario"}]',140,1,6,'codigo',20,false),
  ('banco-de-dados','Joins','Combine informacoes de tabelas relacionadas.','[{"module":"SQL Intermediario","chapter":"Relacoes","title":"JOIN na pratica","text":"JOIN revela dados espalhados em tabelas conectadas.","challenge":"Liste usuarios com progresso da trilha.","validation":"validar join e on","difficulty":"intermediario"}]',150,1,7,'codigo',22,false),
  ('banco-de-dados','Indices e performance','Entenda consultas mais rapidas.','[{"module":"SQL Avancado","chapter":"Performance","title":"Indices","text":"Indices aceleram buscas frequentes quando bem escolhidos.","challenge":"Escolha indice para consulta por user_id e track_id.","validation":"validar create index","difficulty":"avancado"}]',160,1,8,'codigo',24,false),
  ('banco-de-dados','RLS no Supabase','Proteja dados por usuario.','[{"module":"Supabase","chapter":"Seguranca","title":"Row Level Security","text":"RLS impede acesso indevido entre usuarios.","challenge":"Crie policy de select por auth.uid().","validation":"validar enable rls e policy","difficulty":"avancado"}]',170,1,9,'codigo',28,false),
  ('banco-de-dados','Projeto final SQL','Modele progresso de aprendizado.','[{"module":"SQL Projeto","chapter":"Boss","title":"Learning schema","text":"Una tabelas, relacoes, indices e politicas.","challenge":"Modele usuarios, trilhas, licoes e progresso.","validation":"validar schema final","difficulty":"avancado"}]',230,3,10,'projeto',40,true),

  ('ui-ux','Design system','Defina componentes reutilizaveis.','[{"module":"UI Intermediario","chapter":"Sistema","title":"Componentes","text":"Sistemas reduzem variacao e aceleram entregas.","challenge":"Defina botoes, cards, inputs e estados.","validation":"validar componentes e estados","difficulty":"intermediario"}]',120,1,6,'codigo',20,false),
  ('ui-ux','Microcopy','Escreva textos que guiam a acao.','[{"module":"UX","chapter":"Conteudo","title":"Texto funcional","text":"Microcopy reduz duvida e erro.","challenge":"Reescreva mensagens de erro, vazio e sucesso.","validation":"validar estados textuais","difficulty":"intermediario"}]',115,1,7,'codigo',18,false),
  ('ui-ux','Teste de usabilidade','Encontre atritos antes de escalar.','[{"module":"UX","chapter":"Pesquisa","title":"Teste rapido","text":"Observar uso real revela problemas invisiveis no design.","challenge":"Monte checklist de teste para fluxo de onboarding.","validation":"validar checklist e criterios","difficulty":"intermediario"}]',125,1,8,'projeto',22,true),

  ('seguranca-web','XSS na pratica','Previna injecao de scripts.','[{"module":"Seguranca Intermediaria","chapter":"XSS","title":"Entrada perigosa","text":"Nunca renderize HTML de usuario sem sanitizacao.","challenge":"Identifique e corrija um ponto de XSS.","validation":"validar sanitizacao ou escape","difficulty":"intermediario"}]',150,1,6,'codigo',24,false),
  ('seguranca-web','CSRF e sessoes','Proteja acoes autenticadas.','[{"module":"Seguranca Intermediaria","chapter":"Sessoes","title":"Requisicoes confiaveis","text":"CSRF explora sessoes validas em acoes indesejadas.","challenge":"Explique mitigacoes com SameSite e tokens.","validation":"validar conceitos de CSRF","difficulty":"intermediario"}]',145,1,7,'teoria',22,false),
  ('seguranca-web','Segredos e ambiente','Nunca exponha chaves sensiveis.','[{"module":"Seguranca Avancada","chapter":"Secrets","title":"Configuracao segura","text":"Segredos ficam no servidor ou em variaveis protegidas.","challenge":"Classifique variaveis publicas e privadas.","validation":"validar separacao de env","difficulty":"intermediario"}]',150,1,8,'codigo',20,false),
  ('seguranca-web','Projeto final seguranca','Audite uma aplicacao web.','[{"module":"Seguranca Projeto","chapter":"Boss","title":"Security review","text":"Una headers, auth, validacao, XSS e segredos.","challenge":"Crie checklist de hardening para deploy.","validation":"validar checklist completo","difficulty":"avancado"}]',230,3,9,'projeto',38,true),

  ('acessibilidade','Semantica acessivel','Use elementos nativos antes de ARIA.','[{"module":"A11y Basico","chapter":"Semantica","title":"HTML que ajuda","text":"Elementos nativos entregam comportamento acessivel sem codigo extra.","challenge":"Troque divs clicaveis por button, nav e links reais.","validation":"validar elementos nativos","difficulty":"basico"}]',100,1,1,'codigo',14,false),
  ('acessibilidade','Foco visivel','Garanta navegacao por teclado.','[{"module":"A11y Basico","chapter":"Teclado","title":"Onde estou?","text":"Foco visivel mostra a posicao atual para quem usa teclado.","challenge":"Crie estilos :focus-visible para botoes e cards.","validation":"validar focus-visible","difficulty":"basico"}]',105,1,2,'codigo',15,false),
  ('acessibilidade','Contraste','Escolha cores legiveis em estados reais.','[{"module":"A11y Basico","chapter":"Visual","title":"Texto legivel","text":"Contraste ruim impede leitura e cansa usuarios.","challenge":"Ajuste texto, borda e fundo para estados ativo e desativado.","validation":"validar contraste e estados","difficulty":"basico"}]',110,1,3,'codigo',16,false),
  ('acessibilidade','Formularios acessiveis','Labels, erros e ajuda contextual.','[{"module":"A11y Intermediario","chapter":"Forms","title":"Entrada clara","text":"Formulario bom explica o campo, erro e como corrigir.","challenge":"Crie input com label, aria-describedby e mensagem de erro.","validation":"validar label e aria-describedby","difficulty":"intermediario"}]',120,1,4,'codigo',18,false),
  ('acessibilidade','ARIA com criterio','Use roles e labels quando necessario.','[{"module":"A11y Intermediario","chapter":"ARIA","title":"ARIA sem exagero","text":"ARIA complementa semantica quando nativo nao basta.","challenge":"Crie tabs acessiveis com aria-selected e role tablist.","validation":"validar roles e aria-selected","difficulty":"intermediario"}]',130,1,5,'codigo',20,false),
  ('acessibilidade','Leitores de tela','Escreva nomes acessiveis bons.','[{"module":"A11y Intermediario","chapter":"Screen readers","title":"Nome, papel e valor","text":"Componentes precisam comunicar nome, papel e estado.","challenge":"Adicione aria-labels e textos de status em controles iconicos.","validation":"validar labels e estados","difficulty":"intermediario"}]',135,1,6,'codigo',20,false),
  ('acessibilidade','Revisao A11y','Audite uma tela com checklist.','[{"module":"A11y Revisao","chapter":"Auditoria","title":"Checklist inclusivo","text":"Auditoria encontra problemas antes que usuarios encontrem.","challenge":"Revise foco, contraste, labels, headings e teclado.","validation":"validar checklist completo","difficulty":"intermediario"}]',140,1,7,'codigo',24,false),
  ('acessibilidade','Projeto final A11y','Torne um onboarding acessivel.','[{"module":"A11y Projeto","chapter":"Boss","title":"Onboarding inclusivo","text":"Una semantica, foco, contraste, teclado e feedback.","challenge":"Recrie fluxo de onboarding acessivel do inicio ao fim.","validation":"validar fluxo acessivel completo","difficulty":"avancado"}]',210,3,8,'projeto',36,true),

  ('responsividade','Mobile first','Comece pelo menor viewport.','[{"module":"Responsivo Basico","chapter":"Mobile","title":"Pequeno primeiro","text":"Mobile first evita telas pequenas quebradas.","challenge":"Crie layout que funciona antes dos breakpoints.","validation":"validar CSS base mobile","difficulty":"basico"}]',105,1,1,'codigo',15,false),
  ('responsividade','Breakpoints uteis','Use pontos baseados no conteudo.','[{"module":"Responsivo Basico","chapter":"Breakpoints","title":"Quando o layout pede","text":"Breakpoint bom nasce quando o conteudo precisa.","challenge":"Adicione breakpoints para cards e navegacao.","validation":"validar media queries","difficulty":"basico"}]',110,1,2,'codigo',16,false),
  ('responsividade','Grid adaptativo','Use auto-fit e minmax.','[{"module":"Responsivo Intermediario","chapter":"Grid","title":"Grade flexivel","text":"auto-fit cria grids que se reorganizam sozinhos.","challenge":"Crie grid de cards com repeat(auto-fit,minmax()).","validation":"validar auto-fit e minmax","difficulty":"intermediario"}]',125,1,3,'codigo',18,false),
  ('responsividade','Imagens responsivas','Evite cortes e peso excessivo.','[{"module":"Responsivo Intermediario","chapter":"Midia","title":"Imagem certa","text":"Imagens precisam manter proporcao e performance.","challenge":"Use aspect-ratio, object-fit e max-width.","validation":"validar imagem responsiva","difficulty":"intermediario"}]',125,1,4,'codigo',18,false),
  ('responsividade','Tabelas em mobile','Transforme dados densos em UI usavel.','[{"module":"Responsivo Avancado","chapter":"Dados","title":"Tabela sem quebrar","text":"Dados tabulares precisam alternativa em telas pequenas.","challenge":"Crie tabela com scroll controlado ou cards no mobile.","validation":"validar ausencia de overflow horizontal","difficulty":"avancado"}]',140,1,5,'codigo',22,false),
  ('responsividade','Touch targets','Botoes confortaveis para toque.','[{"module":"Responsivo Avancado","chapter":"Interacao","title":"Toque seguro","text":"Alvos pequenos causam erro e frustracao.","challenge":"Ajuste botoes para tamanhos e espacos confortaveis.","validation":"validar dimensoes e gap","difficulty":"intermediario"}]',130,1,6,'codigo',18,false),
  ('responsividade','Revisao responsiva','Teste notebooks, mobile e desktop.','[{"module":"Responsivo Revisao","chapter":"QA","title":"Teste de viewport","text":"Responsividade precisa ser verificada em larguras reais.","challenge":"Corrija tres quebras em tamanhos diferentes.","validation":"validar sem corte e sem overflow","difficulty":"intermediario"}]',140,1,7,'codigo',24,false),
  ('responsividade','Projeto final responsivo','Construa uma pagina multiplataforma.','[{"module":"Responsivo Projeto","chapter":"Boss","title":"Produto fluido","text":"Una mobile first, grids, midia, toque e QA.","challenge":"Crie uma tela completa para celular, notebook e desktop.","validation":"validar layout completo responsivo","difficulty":"avancado"}]',220,3,8,'projeto',38,true),

  ('projetos-praticos','Landing page','Construa uma pagina de produto.','[{"module":"Projetos","chapter":"Landing","title":"Oferta clara","text":"Landing boa comunica valor e leva a acao.","challenge":"Crie hero, beneficios, prova social e CTA.","validation":"validar secoes principais","difficulty":"basico"}]',130,1,1,'projeto',24,false),
  ('projetos-praticos','Dashboard SaaS','Monte interface densa e escaneavel.','[{"module":"Projetos","chapter":"Dashboard","title":"Operacao diaria","text":"Dashboards precisam organizacao, hierarquia e dados claros.","challenge":"Crie cards, tabela, filtros e resumo.","validation":"validar dashboard completo","difficulty":"intermediario"}]',160,1,2,'projeto',30,false),
  ('projetos-praticos','To-do app','Crie app interativo com estado.','[{"module":"Projetos","chapter":"App","title":"Estado e persistencia","text":"Apps reais combinam UI, eventos e dados.","challenge":"Crie tarefas com filtros e localStorage.","validation":"validar CRUD local","difficulty":"intermediario"}]',170,1,3,'projeto',32,false),
  ('projetos-praticos','Cliente de API','Consuma dados e trate erro.','[{"module":"Projetos","chapter":"API","title":"Dados externos","text":"Produto real precisa lidar com carregamento, erro e vazio.","challenge":"Crie lista consumindo API simulada com loading e erro.","validation":"validar estados de dados","difficulty":"intermediario"}]',180,1,4,'projeto',34,false),
  ('projetos-praticos','Area autenticada','Desenhe fluxo de login e perfil.','[{"module":"Projetos","chapter":"Auth","title":"Sessao de usuario","text":"Auth combina formulario, feedback e estado protegido.","challenge":"Crie telas de login, perfil e rota protegida simulada.","validation":"validar fluxo auth","difficulty":"avancado"}]',190,1,5,'projeto',36,false),
  ('projetos-praticos','Portfolio dev','Apresente projetos com qualidade.','[{"module":"Projetos","chapter":"Portfolio","title":"Marca profissional","text":"Portfolio precisa mostrar contexto, papel e resultado.","challenge":"Crie portfolio com projetos, stack e contato.","validation":"validar secoes de portfolio","difficulty":"intermediario"}]',170,1,6,'projeto',30,false),
  ('projetos-praticos','Refatoracao final','Melhore acessibilidade e responsividade.','[{"module":"Projetos","chapter":"Refino","title":"Polimento final","text":"Produtos bons passam por revisao antes de publicar.","challenge":"Audite projeto para A11y, responsividade e performance.","validation":"validar checklist de qualidade","difficulty":"avancado"}]',180,1,7,'codigo',30,false),
  ('projetos-praticos','Capstone CodeQuest','Entregue um produto completo.','[{"module":"Projetos","chapter":"Boss","title":"Produto final","text":"Una HTML, CSS, JS, React, API, acessibilidade e responsividade.","challenge":"Construa um mini produto de aprendizado com progresso e missoes.","validation":"validar entrega capstone","difficulty":"avancado"}]',260,5,8,'projeto',50,true)
) as x(slug,title,description,content,xp,gems,ord,type,minutes,is_boss) on t.slug=x.slug
on conflict do nothing;

insert into public.missions(title,description,type,xp_reward,gem_reward,requirement_type,requirement_value,icon) values
('Aquecimento diario','Conclua uma licao da trilha atual.','daily',80,1,'complete_lessons',1,'📖'),
('Pratica de editor','Abra uma missao e execute uma validacao.','daily',60,1,'run_validation',1,'💻'),
('Revisao rapida','Revise uma licao ja desbloqueada.','daily',70,1,'review_lesson',1,'🔁'),
('Sequencia ativa','Mantenha seu streak de hoje.','daily',50,1,'maintain_streak',1,'🔥'),
('Desafio relampago','Complete um desafio permanente.','daily',90,1,'complete_challenges',1,'⚡'),
('Semana de progresso','Complete cinco licoes durante a semana.','weekly',350,4,'complete_lessons',5,'🗓️'),
('Projeto semanal','Finalize uma licao do tipo projeto.','weekly',420,5,'complete_projects',1,'🚧'),
('Trilha em movimento','Avance pelo menos 30% em uma trilha.','weekly',380,4,'track_progress',30,'🧭'),
('Maratona de desafios','Conclua tres desafios permanentes.','weekly',450,5,'complete_challenges',3,'🏁'),
('Revisao profissional','Complete duas revisoes de fixacao.','weekly',320,3,'complete_reviews',2,'🧪'),
('Evento Frontend Warrior','Construa uma tela responsiva completa.','special',700,10,'special_project',1,'🏆'),
('Boss de Acessibilidade','Passe pelo checklist de acessibilidade.','special',650,8,'a11y_audit',1,'♿'),
('Badge API Hunter','Complete uma missao de APIs com tratamento de erro.','special',620,8,'api_mission',1,'🔌'),
('Deploy Ready','Prepare um fluxo de release com Git/GitHub.','special',680,9,'deploy_flow',1,'🚀'),
('Capstone CodeQuest','Entregue um projeto pratico final.','special',1000,15,'capstone',1,'👑');

insert into public.achievements(slug,title,description,icon,rarity,requirement_type,requirement_value,xp_reward) values
('primeira-missao','Primeira missão','Conclua sua primeira missão.','🏅','common','lessons_completed',1,25),
('primeira-trilha-iniciada','Primeira trilha iniciada','Escolha e inicie sua primeira trilha.','🧭','common','track_started',1,25),
('primeira-trilha-finalizada','Primeira trilha finalizada','Complete uma trilha inteira.','🚀','epic','tracks_completed',1,150),
('xp-100','100 XP','Acumule 100 XP.','🔮','common','xp_total',100,25),
('xp-500','500 XP','Acumule 500 XP.','💎','rare','xp_total',500,75),
('xp-1000','1000 XP','Acumule 1000 XP.','👑','epic','xp_total',1000,120),
('streak-7','7 dias seguidos','Mantenha uma semana de streak.','🔥','epic','streak',7,120),
('streak-30','30 dias seguidos','Mantenha um mes de constancia.','🌋','legendary','streak',30,300),
('html-completo','HTML completo','Finalize a trilha HTML.','🌐','rare','track_html',1,100),
('css-completo','CSS completo','Finalize a trilha CSS.','🎨','rare','track_css',1,100),
('javascript-completo','JavaScript completo','Finalize a trilha JavaScript.','⚡','epic','track_javascript',1,130),
('react-completo','React completo','Finalize a trilha React.','⚛️','epic','track_react',1,150),
('daily-completo','Diária completa','Complete uma missão diária.','☀️','common','daily_missions',1,30),
('weekly-completo','Semanal completa','Complete uma missão semanal.','🗓️','rare','weekly_missions',1,80),
('special-completo','Especial completa','Complete uma missão especial.','🏆','epic','special_missions',1,150),
('a11y-guardian','Guardião A11y','Complete lições de acessibilidade.','♿','rare','lessons_completed',20,100),
('performance-minded','Performance Minded','Acumule progresso avançado em projetos.','⚙️','epic','lessons_completed',40,140),
('codequest-lenda','Lenda CodeQuest','Complete uma longa jornada de aprendizado.','👑','legendary','lessons_completed',80,400)
on conflict(slug) do update set title=excluded.title,description=excluded.description,icon=excluded.icon,rarity=excluded.rarity,requirement_type=excluded.requirement_type,requirement_value=excluded.requirement_value,xp_reward=excluded.xp_reward,is_active=true;

insert into public.devtags(slug,name,description,icon,color,requirement_type,requirement_value) values
('html-semantico','HTML Semantico','Domina estrutura com significado.','🌐','#E44D26','lessons_completed',6),
('css-moderno','CSS Moderno','Usa tokens, estados e CSS atual.','🎨','#2965F1','lessons_completed',10),
('flexbox-pro','Flexbox Pro','Alinha interfaces com flexbox.','↔️','#4DBBFF','lessons_completed',8),
('grid-builder','Grid Builder','Cria layouts com CSS Grid.','▦','#9B6FFF','lessons_completed',12),
('javascript-dom','JavaScript DOM','Manipula interfaces com eventos e DOM.','⚡','#F7DF1E','lessons_completed',14),
('react-hooks','React Hooks','Usa estado, efeitos e hooks proprios.','⚛️','#61DAFB','lessons_completed',24),
('api-hunter','API Hunter','Consome APIs com tratamento de erro.','🔌','#4DBBFF','lessons_completed',28),
('git-collab','Git Collaborator','Trabalha com branches, PRs e releases.','🔀','#F05032','lessons_completed',18),
('deploy-ready','Deploy Ready','Prepara entrega versionada.','🚀','#F5A623','level',4),
('a11y-guardian','A11y Guardian','Cuida de foco, contraste e teclado.','♿','#2ECC71','lessons_completed',20),
('responsive-maker','Responsive Maker','Entrega telas para mobile e desktop.','📱','#4DBBFF','lessons_completed',22),
('performance-minded','Performance Minded','Pensa em carregamento, cache e fluidez.','⚙️','#9B6FFF','xp_total',1000),
('clean-code','Clean Code','Refatora com clareza e consistencia.','🧼','#2ECC71','lessons_completed',30),
('typescript-safe','TypeScript Safe','Modela dados com tipos confiaveis.','🔷','#3178C6','lessons_completed',26),
('backend-builder','Backend Builder','Cria APIs, rotas e validacoes.','🟢','#3C873A','lessons_completed',32),
('database-mapper','Database Mapper','Modela consultas e relacionamentos.','🗄️','#9B6FFF','lessons_completed',34),
('daily-grinder','Daily Grinder','Mantem pratica diaria.','🔥','#FF6B35','streak',7),
('challenge-solver','Challenge Solver','Resolve desafios de fixacao.','🏁','#F5A623','challenges_completed',5),
('track-finisher','Track Finisher','Finaliza uma trilha inteira.','🏆','#FFD166','tracks_completed',1),
('capstone-dev','Capstone Dev','Entrega projetos completos.','👑','#EEEAFF','level',8)
on conflict(slug) do update set name=excluded.name,description=excluded.description,icon=excluded.icon,color=excluded.color,requirement_type=excluded.requirement_type,requirement_value=excluded.requirement_value,is_active=true;

update public.tracks t
set total_lessons=s.lesson_count,
    total_xp=s.total_xp
from (
  select track_id,count(*)::int as lesson_count,coalesce(sum(xp_reward),0)::int as total_xp
  from public.lessons
  where is_active=true
  group by track_id
) s
where t.id=s.track_id;
