insert into public.tracks(slug,title,description,long_description,difficulty,icon,color,total_lessons,total_xp,order_index,tags)
values
  ('frontend','Frontend','Construa interfaces web completas e navegaveis.','Roadmap completo de HTML, CSS, JavaScript, React e Next.js com quests praticas e boss final.','iniciante','FE','#38BDF8',10,0,16,array['frontend','web','roadmap']),
  ('backend','Backend','Crie APIs, regras de negocio e persistencia.','Roadmap de HTTP, Node.js, bancos, auth, testes e deploy de APIs.','intermediario','BE','#22C55E',10,0,17,array['backend','api','roadmap']),
  ('java','Java','Desenvolva aplicacoes robustas com Java.','Roadmap de sintaxe, POO, colecoes, excecoes, Spring Boot e APIs.','iniciante','JV','#F97316',9,0,18,array['backend','java','roadmap']),
  ('php','PHP','Crie sistemas web e APIs com PHP moderno.','Roadmap de PHP, formularios, PDO, MVC, Laravel e seguranca.','iniciante','PHP','#8B5CF6',9,0,19,array['backend','php','roadmap']),
  ('cybersecurity','Cybersecurity','Aprenda fundamentos defensivos e pentest etico.','Roadmap de Linux, redes, HTTP, OWASP, pentest controlado e relatorio final.','intermediario','SEC','#EF4444',9,0,20,array['security','cybersecurity','roadmap']),
  ('ai-engineer','AI Engineer','Construa produtos com IA de ponta a ponta.','Roadmap de Python para IA, dados, embeddings, RAG, agentes, avaliacao e deploy.','intermediario','AI','#A855F7',9,0,21,array['ai','python','roadmap']),
  ('mobile','Mobile','Crie apps mobile com fluxos reais.','Roadmap de UI mobile, React Native, navegacao, estado, APIs, storage e publicacao.','iniciante','APP','#06B6D4',9,0,22,array['mobile','apps','roadmap']),
  ('devops','DevOps','Automatize entrega, infraestrutura e observabilidade.','Roadmap de Linux, Git, Docker, CI/CD, cloud, Kubernetes e monitoramento.','intermediario','OPS','#F59E0B',9,0,23,array['devops','cloud','roadmap']),
  ('game-development','Game Development','Construa jogos jogaveis com logica e polimento.','Roadmap de game loop, input, fisica, fases, UI, audio, build e boss final.','iniciante','GAME','#EC4899',9,0,24,array['games','javascript','roadmap'])
on conflict(slug) do update set
  title=excluded.title,
  description=excluded.description,
  long_description=excluded.long_description,
  difficulty=excluded.difficulty,
  icon=excluded.icon,
  color=excluded.color,
  order_index=excluded.order_index,
  tags=excluded.tags,
  is_active=true;

do $$
declare
  item record;
  v_track_id uuid;
  v_lesson_id uuid;
begin
  for item in
    select * from (values
      ('frontend','HTML Basico','Estruture uma pagina com head, body e conteudo semantico.','[{"module":"Frontend","chapter":"HTML","title":"Documento web","text":"HTML define a estrutura da interface antes de qualquer estilo.","challenge":"Crie uma pagina com header, main, section e footer.","validation":"validar estrutura HTML semantica","difficulty":"basico","quest":"Mapa inicial do navegador"}]',90,1,1,'teoria',14,false),
      ('frontend','Tags HTML','Use headings, paragrafos, listas, links e imagens.','[{"module":"Frontend","chapter":"HTML","title":"Tags essenciais","text":"Tags corretas deixam o conteudo legivel para pessoas, navegadores e leitores de tela.","challenge":"Monte uma secao com h1, p, ul, a e img com alt.","validation":"validar tags essenciais","difficulty":"basico","quest":"Inventario de elementos"}]',100,1,2,'codigo',16,false),
      ('frontend','Forms','Capture dados com labels, inputs e validacao basica.','[{"module":"Frontend","chapter":"Forms","title":"Entrada de dados","text":"Forms precisam de labels claros, tipos corretos e feedback.","challenge":"Crie um formulario de cadastro com email, senha e botao.","validation":"validar label, input e required","difficulty":"basico","quest":"Portal de cadastro"}]',115,1,3,'codigo',18,false),
      ('frontend','CSS Basico','Aplique cores, tipografia, box model e estados simples.','[{"module":"Frontend","chapter":"CSS","title":"Primeira camada visual","text":"CSS transforma estrutura em interface clara e consistente.","challenge":"Estilize um card com espaco, borda e hover.","validation":"validar seletores, padding e hover","difficulty":"basico","quest":"Armadura visual"}]',120,1,4,'codigo',18,false),
      ('frontend','Flexbox','Alinhe barras, cards e acoes com flexbox.','[{"module":"Frontend","chapter":"Layout","title":"Eixo flexivel","text":"Flexbox resolve alinhamento em uma dimensao com controle fino.","challenge":"Crie uma navbar responsiva com display flex.","validation":"validar flex, gap e alinhamento","difficulty":"intermediario","quest":"Ponte dos alinhamentos"}]',135,1,5,'codigo',20,false),
      ('frontend','Grid','Monte layouts em colunas e areas responsivas.','[{"module":"Frontend","chapter":"Layout","title":"Grade de conteudo","text":"CSS Grid organiza paginas inteiras com linhas, colunas e areas.","challenge":"Crie um grid de cards com repeat e minmax.","validation":"validar grid responsivo","difficulty":"intermediario","quest":"Mapa em grade"}]',145,1,6,'codigo',22,false),
      ('frontend','JavaScript','Adicione estado, eventos e manipulacao do DOM.','[{"module":"Frontend","chapter":"JavaScript","title":"Interface viva","text":"JavaScript conecta acoes do usuario a mudancas na tela.","challenge":"Crie um contador com botoes e texto atualizado.","validation":"validar eventos e DOM","difficulty":"intermediario","quest":"Cristal de interacao"}]',155,1,7,'codigo',24,false),
      ('frontend','React','Componentize UI com props, estado e listas.','[{"module":"Frontend","chapter":"React","title":"Componentes reutilizaveis","text":"React organiza telas em componentes com dados previsiveis.","challenge":"Crie lista de cards com props e useState.","validation":"validar componente, props, state e key","difficulty":"intermediario","quest":"Forja de componentes"}]',175,2,8,'codigo',28,false),
      ('frontend','Next.js','Crie rotas, paginas e carregamento de dados.','[{"module":"Frontend","chapter":"Next.js","title":"App web completo","text":"Next.js combina roteamento, renderizacao e estrutura de produto.","challenge":"Crie duas rotas e uma pagina de detalhe com dados simulados.","validation":"validar rotas e composicao","difficulty":"avancado","quest":"Portal das rotas"}]',190,2,9,'codigo',30,false),
      ('frontend','Boss Frontend','Entregue uma interface completa e responsiva.','[{"module":"Frontend","chapter":"Boss","title":"Painel de progresso","text":"Una HTML, forms, CSS, flex, grid, JavaScript, React e Next.js.","challenge":"Construa um painel com cadastro, lista, progresso visual e detalhe navegavel.","validation":"validar produto frontend completo","difficulty":"avancado","quest":"Boss da interface"}]',260,5,10,'projeto',45,true),

      ('backend','HTTP Basico','Entenda request, response, headers e status.','[{"module":"Backend","chapter":"HTTP","title":"Contrato da web","text":"Backends conversam por metodos, rotas, headers e codigos de status.","challenge":"Mapeie uma request GET e uma response JSON.","validation":"validar metodo, rota e status","difficulty":"basico","quest":"Portao HTTP"}]',100,1,1,'teoria',16,false),
      ('backend','Node.js Basico','Suba um servidor e responda dados.','[{"module":"Backend","chapter":"Node.js","title":"Servidor inicial","text":"Node executa JavaScript no servidor para criar APIs.","challenge":"Crie uma rota /health retornando JSON.","validation":"validar servidor e json","difficulty":"basico","quest":"Nucleo do servidor"}]',115,1,2,'codigo',18,false),
      ('backend','Rotas REST','Modele recursos com GET, POST, PATCH e DELETE.','[{"module":"Backend","chapter":"REST","title":"Recursos claros","text":"REST organiza acoes em recursos previsiveis.","challenge":"Crie rotas para listar e criar tarefas.","validation":"validar rotas REST","difficulty":"intermediario","quest":"Mapa de endpoints"}]',135,1,3,'codigo',22,false),
      ('backend','Validacao','Proteja regras antes de processar dados.','[{"module":"Backend","chapter":"Validacao","title":"Entrada confiavel","text":"Toda API deve validar payloads e responder erros uteis.","challenge":"Valide titulo obrigatorio e tamanho minimo.","validation":"validar regras e erro 400","difficulty":"intermediario","quest":"Filtro de entrada"}]',145,1,4,'codigo',22,false),
      ('backend','Banco de Dados','Persista dados com tabelas e relacionamentos.','[{"module":"Backend","chapter":"Banco","title":"Persistencia","text":"Banco guarda estado real e precisa de chaves e filtros.","challenge":"Modele usuarios, tarefas e relacionamento.","validation":"validar tabelas e foreign key","difficulty":"intermediario","quest":"Cofre de dados"}]',160,1,5,'codigo',26,false),
      ('backend','Autenticacao','Controle sessao, tokens e permissoes.','[{"module":"Backend","chapter":"Auth","title":"Identidade","text":"Auth confirma quem esta chamando a API e o que pode acessar.","challenge":"Proteja uma rota usando token simulado.","validation":"validar Authorization e 401","difficulty":"avancado","quest":"Guardiao da sessao"}]',175,2,6,'codigo',28,false),
      ('backend','Testes de API','Verifique respostas, erros e contratos.','[{"module":"Backend","chapter":"Testes","title":"Contrato testado","text":"Testes reduzem regressao em rotas e regras.","challenge":"Escreva casos para sucesso, validacao e nao encontrado.","validation":"validar cenarios de teste","difficulty":"avancado","quest":"Arena de QA"}]',180,2,7,'codigo',30,false),
      ('backend','Cache e Filas','Melhore performance e tarefas demoradas.','[{"module":"Backend","chapter":"Escala","title":"Trabalho eficiente","text":"Cache reduz repeticao e filas desacoplam tarefas lentas.","challenge":"Desenhe cache por chave e uma fila de email.","validation":"validar cache e job","difficulty":"avancado","quest":"Motor de escala"}]',185,2,8,'codigo',30,false),
      ('backend','Deploy de API','Prepare variaveis, logs e ambiente.','[{"module":"Backend","chapter":"Deploy","title":"API no ar","text":"Deploy exige config segura, logs e checks de saude.","challenge":"Defina envs, healthcheck e checklist de release.","validation":"validar checklist de deploy","difficulty":"avancado","quest":"Portal de producao"}]',190,2,9,'codigo',32,false),
      ('backend','Boss Backend','Construa uma API completa de missoes.','[{"module":"Backend","chapter":"Boss","title":"Mission API","text":"Una HTTP, rotas, validacao, banco, auth, testes e deploy.","challenge":"Entregue CRUD de missoes com progresso e protecao por usuario.","validation":"validar API completa","difficulty":"avancado","quest":"Boss da API"}]',275,5,10,'projeto',48,true),

      ('python','Python Basico','Escreva seus primeiros comandos e prints.','[{"module":"Python","chapter":"Sintaxe","title":"Primeiros comandos","text":"Python prioriza leitura e fluxo direto.","challenge":"Crie prints com nome, objetivo e nivel.","validation":"validar print e strings","difficulty":"basico","quest":"Console inicial"}]',90,1,1,'teoria',14,false),
      ('python','Variaveis','Guarde numeros, textos e booleanos.','[{"module":"Python","chapter":"Dados","title":"Valores nomeados","text":"Variaveis tornam dados reutilizaveis no programa.","challenge":"Crie variaveis para xp, nivel e trilha atual.","validation":"validar variaveis e tipos","difficulty":"basico","quest":"Bolsa de dados"}]',100,1,2,'codigo',16,false),
      ('python','Loops','Repita tarefas com for e while.','[{"module":"Python","chapter":"Fluxo","title":"Repeticao controlada","text":"Loops automatizam trabalho repetitivo sem duplicar codigo.","challenge":"Percorra uma lista de missoes e mostre cada titulo.","validation":"validar for e lista","difficulty":"basico","quest":"Trilha repetida"}]',115,1,3,'codigo',18,false),
      ('python','Funcoes','Agrupe logica com parametros e retorno.','[{"module":"Python","chapter":"Funcoes","title":"Blocos reutilizaveis","text":"Funcoes reduzem repeticao e deixam intencao clara.","challenge":"Crie calcular_xp(base, bonus) retornando total.","validation":"validar def e return","difficulty":"basico","quest":"Forja de funcoes"}]',125,1,4,'codigo',20,false),
      ('python','Listas','Modele colecoes, filtros e transformacoes.','[{"module":"Python","chapter":"Colecoes","title":"Sequencias","text":"Listas guardam conjuntos de valores em ordem.","challenge":"Filtre missoes concluidas de uma lista de dicionarios.","validation":"validar lista, dict e filtro","difficulty":"intermediario","quest":"Inventario de missoes"}]',135,1,5,'codigo',22,false),
      ('python','POO','Crie classes para representar entidades.','[{"module":"Python","chapter":"POO","title":"Objetos do dominio","text":"Classes juntam dados e comportamento em modelos claros.","challenge":"Crie classe Trilha com nome, xp e metodo concluir.","validation":"validar class, __init__ e metodo","difficulty":"intermediario","quest":"Classe mestre"}]',150,2,6,'codigo',26,false),
      ('python','APIs','Consuma JSON e trate erros de rede.','[{"module":"Python","chapter":"APIs","title":"Dados externos","text":"Python e forte para integrar APIs e processar respostas.","challenge":"Busque dados simulados e trate status de erro.","validation":"validar request, json e erro","difficulty":"intermediario","quest":"Ponte de dados"}]',165,2,7,'codigo',28,false),
      ('python','Automacao','Leia arquivos, gere relatorios e economize tempo.','[{"module":"Python","chapter":"Automacao","title":"Script util","text":"Automacao transforma tarefas manuais em scripts repetiveis.","challenge":"Leia uma lista de tarefas e gere resumo por status.","validation":"validar leitura e resumo","difficulty":"avancado","quest":"Maquina de rotina"}]',180,2,8,'codigo',30,false),
      ('python','Boss Python','Automatize um relatorio de progresso.','[{"module":"Python","chapter":"Boss","title":"Relatorio CodeQuest","text":"Una variaveis, loops, funcoes, listas, POO, APIs e automacao.","challenge":"Crie script que calcula progresso, busca dados e exporta resumo.","validation":"validar automacao completa","difficulty":"avancado","quest":"Boss da automacao"}]',250,5,9,'projeto',44,true),

      ('java','Java Basico','Entenda classe Main, tipos e saida no console.','[{"module":"Java","chapter":"Sintaxe","title":"Primeiro programa","text":"Java organiza codigo em classes e metodos.","challenge":"Crie uma Main que imprime nome da trilha e XP.","validation":"validar class Main e main","difficulty":"basico","quest":"JVM inicial"}]',95,1,1,'teoria',15,false),
      ('java','Variaveis e Tipos','Use int, double, boolean e String.','[{"module":"Java","chapter":"Tipos","title":"Dados fortes","text":"Tipos explicitos deixam contratos claros.","challenge":"Modele nivel, xp e status premium.","validation":"validar tipos primitivos e String","difficulty":"basico","quest":"Runas tipadas"}]',105,1,2,'codigo',17,false),
      ('java','Condicionais e Loops','Controle fluxo com if, for e while.','[{"module":"Java","chapter":"Fluxo","title":"Decisoes e repeticao","text":"Fluxo controla regras e listas de trabalho.","challenge":"Calcule bonus de XP por streak e liste missoes.","validation":"validar if e for","difficulty":"basico","quest":"Circuito de controle"}]',120,1,3,'codigo',20,false),
      ('java','POO','Modele classes, atributos e metodos.','[{"module":"Java","chapter":"POO","title":"Objetos fortes","text":"POO e central no ecossistema Java.","challenge":"Crie classe Usuario com ganharXp().","validation":"validar classe, campos e metodo","difficulty":"intermediario","quest":"Molde de objetos"}]',145,1,4,'codigo',24,false),
      ('java','Colecoes','Use List, Map e iteracoes.','[{"module":"Java","chapter":"Colecoes","title":"Estruturas uteis","text":"Colecoes armazenam grupos de entidades do dominio.","challenge":"Crie List de licoes e Map de pontuacoes.","validation":"validar List, Map e loop","difficulty":"intermediario","quest":"Biblioteca de dados"}]',155,1,5,'codigo',25,false),
      ('java','Excecoes','Trate falhas com try/catch e mensagens claras.','[{"module":"Java","chapter":"Erros","title":"Falhas controladas","text":"Excecoes separam caminho feliz de erro recuperavel.","challenge":"Valide entrada e lance erro para XP negativo.","validation":"validar throw e catch","difficulty":"intermediario","quest":"Escudo de erros"}]',160,2,6,'codigo',26,false),
      ('java','Spring Boot','Crie endpoints REST com controllers.','[{"module":"Java","chapter":"Spring","title":"API Java","text":"Spring Boot acelera APIs com anotacoes e convencoes.","challenge":"Crie controller de trilhas com GET simples.","validation":"validar controller e mapping","difficulty":"avancado","quest":"Portal Spring"}]',185,2,7,'codigo',32,false),
      ('java','Persistencia','Use repositories e DTOs para dados.','[{"module":"Java","chapter":"Dados","title":"Camada persistente","text":"APIs Java separam entidade, DTO e repositorio.","challenge":"Modele LessonDto e repository simulado.","validation":"validar DTO e repository","difficulty":"avancado","quest":"Arquivo persistente"}]',190,2,8,'codigo',34,false),
      ('java','Boss Java','Construa uma API Java de progresso.','[{"module":"Java","chapter":"Boss","title":"Progress API","text":"Una sintaxe, POO, colecoes, excecoes, Spring e persistencia.","challenge":"Entregue API de usuarios, trilhas e conclusao de licoes.","validation":"validar API Java completa","difficulty":"avancado","quest":"Boss da JVM"}]',265,5,9,'projeto',48,true),

      ('php','PHP Basico','Entenda tags PHP, variaveis e echo.','[{"module":"PHP","chapter":"Sintaxe","title":"Servidor dinamico","text":"PHP gera respostas dinamicas no servidor.","challenge":"Crie uma pagina que mostra trilha e XP.","validation":"validar tags PHP e echo","difficulty":"basico","quest":"Script inicial"}]',90,1,1,'teoria',14,false),
      ('php','Arrays','Modele listas associativas e numericas.','[{"module":"PHP","chapter":"Dados","title":"Arrays flexiveis","text":"Arrays em PHP servem para listas e mapas.","challenge":"Crie array de licoes com titulo e XP.","validation":"validar array e foreach","difficulty":"basico","quest":"Inventario PHP"}]',105,1,2,'codigo',17,false),
      ('php','Forms e Requests','Receba dados por GET e POST com validacao.','[{"module":"PHP","chapter":"Web","title":"Entrada HTTP","text":"Apps PHP frequentemente processam formularios.","challenge":"Valide nome e email enviados por POST.","validation":"validar POST e required","difficulty":"basico","quest":"Portao do form"}]',125,1,3,'codigo',20,false),
      ('php','Funcoes','Organize regras em funcoes reutilizaveis.','[{"module":"PHP","chapter":"Funcoes","title":"Regras claras","text":"Funcoes deixam templates e regras menos misturados.","challenge":"Crie funcao calcularNivel($xp).","validation":"validar function e return","difficulty":"intermediario","quest":"Alquimia de funcoes"}]',130,1,4,'codigo',21,false),
      ('php','PDO e SQL','Conecte banco com prepared statements.','[{"module":"PHP","chapter":"Banco","title":"SQL seguro","text":"Prepared statements ajudam a evitar SQL injection.","challenge":"Monte uma query preparada para buscar usuario.","validation":"validar PDO e bind","difficulty":"intermediario","quest":"Cofre SQL"}]',160,2,5,'codigo',28,false),
      ('php','MVC','Separe controller, model e view.','[{"module":"PHP","chapter":"Arquitetura","title":"Camadas","text":"MVC reduz acoplamento entre rota, dados e tela.","challenge":"Desenhe arquivos para controller de licoes.","validation":"validar separacao MVC","difficulty":"intermediario","quest":"Castelo MVC"}]',165,2,6,'codigo',28,false),
      ('php','Laravel Basico','Use rotas, controllers e migrations.','[{"module":"PHP","chapter":"Laravel","title":"Framework produtivo","text":"Laravel fornece estrutura moderna para apps PHP.","challenge":"Crie rota e controller para listar trilhas.","validation":"validar rota Laravel e controller","difficulty":"avancado","quest":"Portal Laravel"}]',185,2,7,'codigo',34,false),
      ('php','Seguranca PHP','Proteja sessao, CSRF e saida HTML.','[{"module":"PHP","chapter":"Seguranca","title":"Defesas web","text":"Escape de saida e CSRF sao essenciais em apps server-rendered.","challenge":"Aplique htmlspecialchars e token CSRF conceitual.","validation":"validar escape e CSRF","difficulty":"avancado","quest":"Escudo PHP"}]',190,2,8,'codigo',34,false),
      ('php','Boss PHP','Construa um mini sistema de trilhas.','[{"module":"PHP","chapter":"Boss","title":"Sistema CodeQuest","text":"Una PHP, arrays, forms, funcoes, PDO, MVC, Laravel e seguranca.","challenge":"Entregue CRUD de licoes com formulario, banco e protecoes.","validation":"validar sistema PHP completo","difficulty":"avancado","quest":"Boss do servidor PHP"}]',260,5,9,'projeto',46,true),

      ('cybersecurity','Linux Basico','Navegue, leia arquivos e use permissoes.','[{"module":"Cybersecurity","chapter":"Linux","title":"Terminal seguro","text":"Linux e base de servidores e laboratorios de seguranca.","challenge":"Use comandos para listar, ler e verificar permissoes.","validation":"validar ls, cat e chmod conceitual","difficulty":"basico","quest":"Terminal base"}]',100,1,1,'teoria',16,false),
      ('cybersecurity','Redes','Entenda IP, portas, DNS e TCP.','[{"module":"Cybersecurity","chapter":"Redes","title":"Caminho do pacote","text":"Ataques e defesas dependem de entender rede.","challenge":"Mapeie fluxo cliente DNS HTTP servidor.","validation":"validar IP, DNS, porta e TCP","difficulty":"basico","quest":"Mapa de rede"}]',120,1,2,'codigo',20,false),
      ('cybersecurity','HTTP','Analise headers, cookies, metodos e status.','[{"module":"Cybersecurity","chapter":"Web","title":"HTTP visivel","text":"Muitas falhas aparecem no contrato HTTP.","challenge":"Classifique headers seguros e inseguros.","validation":"validar headers e cookies","difficulty":"basico","quest":"Lupa HTTP"}]',130,1,3,'codigo',22,false),
      ('cybersecurity','OWASP','Conheca XSS, SQLi, auth quebrada e exposicao.','[{"module":"Cybersecurity","chapter":"OWASP","title":"Riscos principais","text":"OWASP organiza riscos recorrentes em aplicacoes web.","challenge":"Associe vulnerabilidades a mitigacoes.","validation":"validar XSS, SQLi e auth","difficulty":"intermediario","quest":"Codex OWASP"}]',150,2,4,'teoria',26,false),
      ('cybersecurity','Reconhecimento','Colete informacoes de forma etica e autorizada.','[{"module":"Cybersecurity","chapter":"Pentest","title":"Recon etico","text":"Pentest comeca por escopo, autorizacao e inventario.","challenge":"Crie checklist de reconhecimento permitido.","validation":"validar escopo e checklist","difficulty":"intermediario","quest":"Radar autorizado"}]',160,2,5,'codigo',28,false),
      ('cybersecurity','Pentest Web','Teste validacao, auth e controle de acesso.','[{"module":"Cybersecurity","chapter":"Pentest","title":"Teste controlado","text":"Pentest procura falhas sem causar dano e registra evidencias.","challenge":"Analise uma rota vulneravel simulada e proponha correcao.","validation":"validar teste e mitigacao","difficulty":"intermediario","quest":"Arena controlada"}]',175,2,6,'codigo',30,false),
      ('cybersecurity','Exploracao Segura','Reproduza falhas em laboratorio isolado.','[{"module":"Cybersecurity","chapter":"Exploracao","title":"Laboratorio","text":"Exploracao deve acontecer apenas em ambientes autorizados.","challenge":"Demonstre impacto de input nao validado em exemplo local.","validation":"validar laboratorio e correcao","difficulty":"avancado","quest":"Simulador seguro"}]',185,2,7,'codigo',32,false),
      ('cybersecurity','Relatorio e Hardening','Documente risco, impacto e correcao.','[{"module":"Cybersecurity","chapter":"Defesa","title":"Relatorio util","text":"O valor do pentest esta na correcao clara e priorizada.","challenge":"Escreva achado com severidade, evidencia e fix.","validation":"validar relatorio completo","difficulty":"avancado","quest":"Arquivo de defesa"}]',190,2,8,'codigo',34,false),
      ('cybersecurity','Boss Cybersecurity','Audite uma aplicacao web completa.','[{"module":"Cybersecurity","chapter":"Boss","title":"Security audit","text":"Una Linux, redes, HTTP, OWASP, pentest, exploracao segura e hardening.","challenge":"Entregue auditoria com checklist, evidencias e plano de correcao.","validation":"validar auditoria final","difficulty":"avancado","quest":"Boss de seguranca"}]',280,5,9,'projeto',50,true),

      ('ai-engineer','Python para IA','Prepare scripts, funcoes e ambiente.','[{"module":"AI Engineer","chapter":"Base","title":"Python aplicado","text":"Produtos de IA precisam de Python organizado e reproducivel.","challenge":"Crie funcao para normalizar prompts de entrada.","validation":"validar funcao e teste simples","difficulty":"basico","quest":"Kernel inicial"}]',110,1,1,'teoria',18,false),
      ('ai-engineer','Dados','Limpe, divida e valide datasets pequenos.','[{"module":"AI Engineer","chapter":"Dados","title":"Base confiavel","text":"Qualidade de dados define qualidade do sistema de IA.","challenge":"Remova duplicados e separe treino e avaliacao simulados.","validation":"validar limpeza e split","difficulty":"basico","quest":"Mineracao de dados"}]',130,1,2,'codigo',22,false),
      ('ai-engineer','Prompts','Projete instrucoes, exemplos e formatos de saida.','[{"module":"AI Engineer","chapter":"Prompting","title":"Instrucao precisa","text":"Prompts bons controlam contexto, objetivo e criterio de resposta.","challenge":"Crie prompt com papel, tarefa, contexto e schema JSON.","validation":"validar estrutura de prompt","difficulty":"intermediario","quest":"Pergaminho de prompt"}]',145,1,3,'codigo',24,false),
      ('ai-engineer','Embeddings','Transforme texto em vetores pesquisaveis.','[{"module":"AI Engineer","chapter":"Busca","title":"Similaridade","text":"Embeddings permitem busca semantica e recomendacao.","challenge":"Modele documentos, vetores e consulta por similaridade.","validation":"validar fluxo de embeddings","difficulty":"intermediario","quest":"Mapa vetorial"}]',160,2,4,'codigo',28,false),
      ('ai-engineer','RAG','Combine recuperacao de contexto com geracao.','[{"module":"AI Engineer","chapter":"RAG","title":"Resposta com contexto","text":"RAG reduz alucinacao ao buscar fontes antes de responder.","challenge":"Desenhe pipeline retrieve, rank e answer.","validation":"validar pipeline RAG","difficulty":"intermediario","quest":"Biblioteca viva"}]',175,2,5,'codigo',30,false),
      ('ai-engineer','Agentes','Orquestre ferramentas, memoria e decisoes.','[{"module":"AI Engineer","chapter":"Agentes","title":"Fluxo autonomo","text":"Agentes combinam modelo, ferramentas e criterios de parada.","challenge":"Modele agente que escolhe entre buscar, calcular e responder.","validation":"validar tools e controle","difficulty":"avancado","quest":"Oficina de agentes"}]',190,2,6,'codigo',34,false),
      ('ai-engineer','Avaliacao','Meca qualidade, seguranca e regressao.','[{"module":"AI Engineer","chapter":"Evals","title":"Qualidade medida","text":"Sistemas de IA precisam de testes com exemplos e rubricas.","challenge":"Crie rubrica para avaliar respostas de tutor de codigo.","validation":"validar criterios e dataset","difficulty":"avancado","quest":"Arena de avaliacao"}]',195,2,7,'codigo',34,false),
      ('ai-engineer','Deploy de IA','Prepare API, logs, custos e fallback.','[{"module":"AI Engineer","chapter":"Deploy","title":"IA em producao","text":"Produto de IA precisa controlar latencia, custo, logs e falhas.","challenge":"Defina endpoint, limites, cache e fallback.","validation":"validar arquitetura de deploy","difficulty":"avancado","quest":"Portal de inferencia"}]',205,2,8,'codigo',36,false),
      ('ai-engineer','Boss AI Engineer','Construa um tutor RAG com avaliacao.','[{"module":"AI Engineer","chapter":"Boss","title":"Tutor inteligente","text":"Una Python, dados, prompts, embeddings, RAG, agentes, evals e deploy.","challenge":"Entregue arquitetura de tutor com busca, resposta, avaliacao e monitoramento.","validation":"validar produto de IA completo","difficulty":"avancado","quest":"Boss da IA"}]',300,5,9,'projeto',55,true),

      ('mobile','Mobile Basico','Entenda telas, componentes e area segura.','[{"module":"Mobile","chapter":"UI","title":"Tela pequena","text":"Mobile exige hierarquia clara, toque confortavel e estados rapidos.","challenge":"Desenhe uma tela de trilha com titulo, lista e acao principal.","validation":"validar estrutura mobile","difficulty":"basico","quest":"Viewport de bolso"}]',100,1,1,'teoria',16,false),
      ('mobile','React Native','Crie componentes com View, Text e Pressable.','[{"module":"Mobile","chapter":"React Native","title":"Componentes nativos","text":"React Native usa componentes que renderizam UI nativa.","challenge":"Monte card de licao com Pressable e textos.","validation":"validar View, Text e Pressable","difficulty":"basico","quest":"Kit nativo"}]',120,1,2,'codigo',20,false),
      ('mobile','Navegacao','Organize stacks, tabs e parametros.','[{"module":"Mobile","chapter":"Navegacao","title":"Fluxo entre telas","text":"Apps precisam levar o usuario entre listas, detalhes e configuracoes.","challenge":"Modele stack de trilhas e detalhe da missao.","validation":"validar rotas e params","difficulty":"intermediario","quest":"Mapa de telas"}]',140,1,3,'codigo',24,false),
      ('mobile','Estado','Controle progresso, loading e erro.','[{"module":"Mobile","chapter":"Estado","title":"UI previsivel","text":"Estado mostra onde o app esta e o que o usuario pode fazer.","challenge":"Crie estado para lessons, selectedLesson e loading.","validation":"validar useState e estados","difficulty":"intermediario","quest":"Cristal de estado"}]',150,1,4,'codigo',26,false),
      ('mobile','APIs Mobile','Consuma dados com loading, erro e retry.','[{"module":"Mobile","chapter":"Dados","title":"Rede instavel","text":"Mobile precisa lidar com conexao lenta ou ausente.","challenge":"Crie chamada fetch com loading, erro e tentar novamente.","validation":"validar fetch e retry","difficulty":"intermediario","quest":"Antena de dados"}]',165,2,5,'codigo',30,false),
      ('mobile','Storage','Salve preferencias e progresso local.','[{"module":"Mobile","chapter":"Persistencia","title":"Memoria local","text":"Storage melhora continuidade mesmo sem internet.","challenge":"Salve trilha selecionada e tema localmente.","validation":"validar AsyncStorage conceitual","difficulty":"intermediario","quest":"Mochila offline"}]',170,2,6,'codigo',30,false),
      ('mobile','Performance','Otimize listas, imagens e re-renderizacao.','[{"module":"Mobile","chapter":"Performance","title":"App fluido","text":"Apps precisam responder rapido ao toque e rolagem.","challenge":"Aplique FlatList e memoizacao em lista longa.","validation":"validar FlatList e memo","difficulty":"avancado","quest":"Motor fluido"}]',185,2,7,'codigo',34,false),
      ('mobile','Publicacao','Prepare build, versao e checklist de loja.','[{"module":"Mobile","chapter":"Release","title":"App publicavel","text":"Publicar exige versao, icones, permissoes e testes.","challenge":"Monte checklist de release Android/iOS.","validation":"validar checklist de loja","difficulty":"avancado","quest":"Portal da loja"}]',190,2,8,'codigo',34,false),
      ('mobile','Boss Mobile','Construa um app de progresso de trilhas.','[{"module":"Mobile","chapter":"Boss","title":"CodeQuest App","text":"Una UI mobile, React Native, navegacao, estado, APIs, storage, performance e release.","challenge":"Entregue fluxo de trilhas, missoes e progresso local sincronizavel.","validation":"validar app mobile completo","difficulty":"avancado","quest":"Boss mobile"}]',280,5,9,'projeto',50,true),

      ('devops','Linux e Shell','Automatize tarefas com comandos e scripts.','[{"module":"DevOps","chapter":"Linux","title":"Base operacional","text":"DevOps comeca com dominio de terminal, arquivos e processos.","challenge":"Crie script para checar status de servico.","validation":"validar shell e exit code","difficulty":"basico","quest":"Console operacional"}]',110,1,1,'teoria',18,false),
      ('devops','Git Flow','Organize branches, releases e revisao.','[{"module":"DevOps","chapter":"Git","title":"Fluxo de entrega","text":"Git conecta desenvolvimento a entrega confiavel.","challenge":"Desenhe fluxo feature, PR, main e tag.","validation":"validar fluxo Git","difficulty":"basico","quest":"Trilho de release"}]',125,1,2,'codigo',20,false),
      ('devops','Docker','Containerize uma aplicacao simples.','[{"module":"DevOps","chapter":"Containers","title":"Ambiente portavel","text":"Docker empacota app, runtime e dependencias.","challenge":"Crie Dockerfile conceitual para API Node.","validation":"validar Dockerfile","difficulty":"intermediario","quest":"Capsula Docker"}]',155,2,3,'codigo',28,false),
      ('devops','Docker Compose','Suba app, banco e rede local.','[{"module":"DevOps","chapter":"Containers","title":"Stack local","text":"Compose orquestra servicos para desenvolvimento e testes.","challenge":"Modele app + postgres com volumes e envs.","validation":"validar compose services","difficulty":"intermediario","quest":"Orquestra local"}]',165,2,4,'codigo',30,false),
      ('devops','CI/CD','Automatize testes, build e deploy.','[{"module":"DevOps","chapter":"CI/CD","title":"Pipeline","text":"Pipelines reduzem erro manual e aceleram entrega.","challenge":"Crie workflow com install, test e build.","validation":"validar etapas CI","difficulty":"intermediario","quest":"Esteira automatica"}]',175,2,5,'codigo',32,false),
      ('devops','Cloud Basico','Entenda regioes, envs, secrets e logs.','[{"module":"DevOps","chapter":"Cloud","title":"Infra gerenciada","text":"Cloud exige configuracao segura e observavel.","challenge":"Defina envs, secrets e healthcheck para deploy.","validation":"validar config cloud","difficulty":"avancado","quest":"Nuvem controlada"}]',185,2,6,'codigo',34,false),
      ('devops','Kubernetes','Compreenda pods, services e deployments.','[{"module":"DevOps","chapter":"Kubernetes","title":"Orquestracao","text":"Kubernetes gerencia containers em escala.","challenge":"Modele deployment e service para uma API.","validation":"validar deployment e service","difficulty":"avancado","quest":"Cluster mestre"}]',205,2,7,'codigo',38,false),
      ('devops','Observabilidade','Monitore logs, metricas e alertas.','[{"module":"DevOps","chapter":"Observabilidade","title":"Sistema visivel","text":"Producao precisa mostrar saude antes do usuario reclamar.","challenge":"Defina metricas, logs e alerta para erro 500.","validation":"validar metricas e alerta","difficulty":"avancado","quest":"Torre de sinais"}]',200,2,8,'codigo',36,false),
      ('devops','Boss DevOps','Entregue pipeline de producao completo.','[{"module":"DevOps","chapter":"Boss","title":"Deploy confiavel","text":"Una Linux, Git, Docker, Compose, CI/CD, cloud, Kubernetes e observabilidade.","challenge":"Crie plano de entrega com pipeline, infraestrutura e monitoramento.","validation":"validar plataforma DevOps completa","difficulty":"avancado","quest":"Boss da entrega"}]',295,5,9,'projeto',55,true),

      ('game-development','Game Loop','Entenda update, render e tempo.','[{"module":"Game Development","chapter":"Fundamentos","title":"Coracao do jogo","text":"Todo jogo alterna leitura de estado, atualizacao e desenho.","challenge":"Modele loop com update(delta) e render().","validation":"validar game loop","difficulty":"basico","quest":"Motor inicial"}]',100,1,1,'teoria',16,false),
      ('game-development','Input','Capture teclado, mouse ou toque.','[{"module":"Game Development","chapter":"Controle","title":"Comandos do jogador","text":"Input transforma intencao do jogador em acao no mundo.","challenge":"Mapeie setas para mover personagem.","validation":"validar input e movimento","difficulty":"basico","quest":"Controle ativado"}]',120,1,2,'codigo',20,false),
      ('game-development','Sprites e Animacao','Desenhe estados visuais e frames.','[{"module":"Game Development","chapter":"Visual","title":"Personagem vivo","text":"Sprites e animacoes comunicam acao, dano e movimento.","challenge":"Crie estados idle, walk e hit conceituais.","validation":"validar estados de animacao","difficulty":"intermediario","quest":"Folha de sprites"}]',140,1,3,'codigo',24,false),
      ('game-development','Colisao','Detecte contato entre jogador, chao e itens.','[{"module":"Game Development","chapter":"Fisica","title":"Contato","text":"Colisao define limites, coleta e dano.","challenge":"Implemente colisao AABB conceitual entre retangulos.","validation":"validar AABB","difficulty":"intermediario","quest":"Muralha fisica"}]',155,2,4,'codigo',28,false),
      ('game-development','Fases','Organize mapa, objetivos e progressao.','[{"module":"Game Development","chapter":"Level Design","title":"Mapa jogavel","text":"Fases guiam aprendizado, desafio e recompensa.","challenge":"Crie fase com inicio, obstaculo, item e saida.","validation":"validar estrutura de fase","difficulty":"intermediario","quest":"Mapa da dungeon"}]',165,2,5,'codigo',30,false),
      ('game-development','UI e HUD','Mostre vida, XP, tempo e feedback.','[{"module":"Game Development","chapter":"HUD","title":"Informacao clara","text":"HUD precisa informar sem atrapalhar o jogo.","challenge":"Desenhe HUD com vida, XP e objetivo atual.","validation":"validar HUD e feedback","difficulty":"intermediario","quest":"Painel do heroi"}]',170,2,6,'codigo',30,false),
      ('game-development','Audio e Juice','Adicione impacto com som, particulas e camera.','[{"module":"Game Development","chapter":"Polimento","title":"Sensacao de jogo","text":"Juice aumenta resposta emocional sem mudar a regra central.","challenge":"Planeje som, shake e particulas para coleta de item.","validation":"validar feedbacks de jogo","difficulty":"avancado","quest":"Polimento arcano"}]',185,2,7,'codigo',34,false),
      ('game-development','Build e Publicacao','Prepare versao jogavel e checklist.','[{"module":"Game Development","chapter":"Release","title":"Jogo entregavel","text":"Build precisa carregar assets, iniciar rapido e explicar controles.","challenge":"Monte checklist de release web do jogo.","validation":"validar checklist de build","difficulty":"avancado","quest":"Portal do build"}]',190,2,8,'codigo',34,false),
      ('game-development','Boss Game Dev','Crie um mini jogo completo.','[{"module":"Game Development","chapter":"Boss","title":"Arena CodeQuest","text":"Una game loop, input, sprites, colisao, fases, HUD, audio, polimento e build.","challenge":"Entregue mini jogo com objetivo, progressao, recompensas e tela final.","validation":"validar jogo completo","difficulty":"avancado","quest":"Boss do jogo"}]',285,5,9,'projeto',52,true)
    ) as lesson(slug,title,description,content,xp,gems,ord,type,minutes,is_boss)
  loop
    select id into v_track_id
    from public.tracks
    where slug = item.slug;

    if v_track_id is null then
      raise exception 'Track not found for slug %', item.slug;
    end if;

    select id into v_lesson_id
    from public.lessons
    where track_id = v_track_id
      and order_index = item.ord
      and is_active = true
    order by created_at asc, id asc
    limit 1;

    if v_lesson_id is null then
      insert into public.lessons(track_id,title,description,content,xp_reward,gem_reward,order_index,type,estimated_minutes,is_boss,is_active)
      values(v_track_id,item.title,item.description,item.content::jsonb,item.xp,item.gems,item.ord,item.type,item.minutes,item.is_boss,true);
    else
      update public.lessons
      set title = item.title,
          description = item.description,
          content = item.content::jsonb,
          xp_reward = item.xp,
          gem_reward = item.gems,
          type = item.type,
          estimated_minutes = item.minutes,
          is_boss = item.is_boss,
          is_active = true
      where id = v_lesson_id;
    end if;
  end loop;
end;
$$;

update public.tracks t
set total_lessons = stats.lesson_count,
    total_xp = stats.total_xp
from (
  select track_id, count(*)::int as lesson_count, coalesce(sum(xp_reward),0)::int as total_xp
  from public.lessons
  where is_active = true
  group by track_id
) stats
where t.id = stats.track_id;
